### ISSUE TITLE
I have a request for you

### ISSUE THREAD

**Issue by be7kt88945779k** [blueskythlikesclouds/MikuMikuLibrary#14]
Hello,blueskythlikesclouds, nice to meet u.

I am using ur miku tools, it's really helpful, I'm really appreciate it.
Thank you so much.

But i have requests for you, could you please making more powerful miku motion data editor just like DeXd or alXve 5 Movie Data Tool?

Please help, thanks.

**Comment by blueskythlikesclouds** [comment]
You're asking for a motion editor like in MMD?

**Comment by be7kt88945779k** [comment]
> You're asking for a motion editor like in MMD?
Yes,i want to show edited motion with project diva  arcade or project diva future tone arcade,i mean i need to use edited motion data replace to original file(farc).

It is my request,I wish u can making an motion editor for project diva  arcade just like MMD or movie data tool.

**Comment by blueskythlikesclouds** [comment]
I'm not sure if I'll be making an actual motion editor like MMD but there will be an FBX importer. (also possibly VMD)

**Comment by be7kt88945779k** [comment]
i'm counting on you, i just want editing orignlal motion data from Project diva.

**Comment by blueskythlikesclouds** [comment]
Haha, sure. The next release is going to be pretty big, and it's going to have the ability to import custom motions.

**Comment by be7kt88945779k** [comment]
Great!! that will be help

**Comment by be7kt88945779k** [comment]
Hello,it's me again.
How is it going with your updates?
Would i meet your program in this few days?

**Comment by blueskythlikesclouds** [comment]
No, I'm afraid it's going to take a lot of time to be finished. There's so much to do.

**Comment by be7kt88945779k** [comment]
That’s a shame.
Anyway,Keep it up
It's look like next version will be more powerful.

**Comment by be7kt88945779k** [comment]
how is going?
When will you new version be released?
