### ISSUE TITLE
A color issue

### ISSUE THREAD

**Issue by Charl-Ep** [blueskythlikesclouds/MikuMikuLibrary#17]
Hello blueskythlikesclouds:
Your tools are really amazing. Thanks for your work \(-0-)/
I've found some issue when I trying to replace a texture, the tool will automatically reduce every RGB value to the nearest multiple of eight. for example (240,220,200) will change to (232,216,192).
39

**Comment by Waelwindows** [comment]
Could you specify the texture compression you're saving into? e.g. DXT5, RGB, etc
As it's likely to be the compression

**Comment by blueskythlikesclouds** [comment]
What format are you trying to replace the texture with? PNG?
It'd help if you also mentioned what texture you are trying to replace.

**Comment by Charl-Ep** [comment]
yeah i think that's a compression issue. thanks
