### ISSUE TITLE
Add a feature too add sprites inside MMM

### ISSUE THREAD

**Issue by BroGamer4256** [blueskythlikesclouds/MikuMikuLibrary#19]
using C# samyuu has proven by using MML as a reference you can create a program to add sprites with this code https://discordapp.com/channels/531630856767406105/613450757227937792/710428160306577439
So its not out of the realm of possibility to add a feature to add Sprites inside MMM. Could be quite useful

**Comment by blueskythlikesclouds** [comment]
It's already in the unstable version.

**Comment by blueskythlikesclouds** [comment]
Implemented as of 6621d59
