### ISSUE TITLE
Cannot Export As FBX

### ISSUE THREAD

**Issue by VRArt1** [blueskythlikesclouds/MikuMikuLibrary#2]
Using MikuMikuModel I can't seem to export as an fbx file. I get an error popup and no exported fbx file.

**Comment by blueskythlikesclouds** [comment]
Yeah, in the wiki it's also mentioned to export as DAE only. Assimp can't export FBXs yet.

**Comment by blueskythlikesclouds** [comment]
Implemented as of 76b07f7.
