### ISSUE TITLE
Incorrect RGB8 DDS texture export

### ISSUE THREAD

**Issue by samyuu** [blueskythlikesclouds/MikuMikuLibrary#20]
Attempting to export textures that are stored as uncompressed 24-bit RGB will produce ill-formatted DDS files that crash or fail to open in image editors such as Photoshop or GIMP.
The exact part of the the output DDS header that causes this is unknown to me.
Mostly affected by this are DIVA F style toon curve textures.

**Comment by blueskythlikesclouds** [comment]
nani

**Comment by Waelwindows** [comment]
[Here's](https://mega.nz/file/gplGiQSB) a sample from `mikitm001_tex.bin` with correct headers

**Comment by blueskythlikesclouds** [comment]
Fixed as of 76b07f7.
