### ISSUE TITLE
Saving an F2nd OSD file doesn't automatically update it's corresponding TXI file.

### ISSUE THREAD

**Issue by thatrandomlurker-divamoddingtools** [blueskythlikesclouds/MikuMikuLibrary#23]
unsure as of which build this started happening in, but in 2.0.2 the osd saving feature fails to update the txi file with texture names. note that i am using a correct configuration for the model file, as seen in the attached screenshot
![Untitled](https://user-images.githubusercontent.com/59970354/88500369-1a889900-cfa3-11ea-900c-69ac0641ef29.png)
. a workaround as of now is to simply export the modified model, as it successfully creates a txi file when exporting said model before saving, though i don't think this behavior is intended.

**Comment by blueskythlikesclouds** [comment]
I can't reproduce the problem. Replacing an .osd file (in the .farc) updates the .txi file properly.

**Comment by thatrandomlurker-divamoddingtools** [comment]
sorry, that was an error on my part.
