### ISSUE TITLE
Type initializer threw an exception

### ISSUE THREAD

**Issue by domaug** [blueskythlikesclouds/MikuMikuLibrary#26]
I apologize if this is a silly question, but every time I try to export a texture, not only will it not load, but it will also give me an error message saying "The type initializer for 'MikuMikuLibrary.Native' threw an exception."  Is my computer missing something that isn't allowing it to run properly?  

For context, I'm opening up .farc files in Virtua Fighter 5: Final Showdown and trying to extract textures from character item sets.

Thank you!

**Comment by blueskythlikesclouds** [comment]
I know this is closed, but other people might see this so I'll tell the solution anyway.

Install the dependencies and unblock the .dll files as explained in the releases page.
