### ISSUE TITLE
Manual or automatic conversion to ATI2 YCBCR when replacing textures

### ISSUE THREAD

**Issue by Akatsukidarkx** [blueskythlikesclouds/MikuMikuLibrary#28]
Would it be possible to add this option in the future?

For example, if a MERGE_BC5COMP_2 texture has the ATI2 YCBCR format, the same format can be kept when replacing that texture. 

This is because although the DXT5 format has worked for me so far, in some .farc files where I use this format and not the original (YCBCR) it gives me problems when loading other textures, in this case the previews of the videos in PSVITA (The previews do not load at first).  So far, that would be the only problem I have had with MMM in all this time.

[https://drive.google.com/file/d/12Qvbg9IdVZ-iQ1zmQpYpVLfvXJaLoCYj/view?usp=sharing](url)

**Comment by blueskythlikesclouds** [comment]
Both are implemented as of 7021784.
I also added more formats just for the sake of it.
