### ISSUE TITLE
MikuMikuModel crash

### ISSUE THREAD

**Issue by WM86** [blueskythlikesclouds/MikuMikuLibrary#3]
open the modle will crash in Windows10 1809.

**Comment by blueskythlikesclouds** [comment]
Do you have an Intel HD Graphics GPU?

**Comment by blueskythlikesclouds** [comment]
What kind of a crash is it, may I ask?
Does it show a message box with an error code in it, or does it absurdly crash with no message, and just "MikuMikuModel has stopped working"?

**Comment by Omoinemie** [comment]
> What kind of a crash is it, may I ask?
> Does it show a message box with an error code in it, or does it crash with only "MikuMikuModel has stopped working"?

nothing！
![1](https://user-images.githubusercontent.com/31991443/49326592-5598b600-f58f-11e8-8d9e-d46567bdccc2.gif)

**Comment by blueskythlikesclouds** [comment]
Windows 10 has removed the crash dialog in one of the major updates, so when a program is supposed to show "has stopped working" dialog, the program directly closes itself.

Maybe MMM is picking your Intel HD Graphics instead of your NVIDIA GPU. Try running MMM with your NVIDIA?

**Comment by Omoinemie** [comment]
I closed the intel HD Graphics and still the same as before.

**Comment by blueskythlikesclouds** [comment]
Well, this is weird...
Are you able to load/preview textures or sprites?

**Comment by Omoinemie** [comment]
> Well, this is weird...
> Are you able to load/preview textures or sprites?

yes

**Comment by Omoinemie** [comment]
> Well, this is weird...
> Are you able to load/preview textures or sprites?


![snipaste_2018-12-01_19-51-35](https://user-images.githubusercontent.com/31991443/49327913-86361b00-f5a2-11e8-8767-b6bca718aedd.jpg)

**Comment by blueskythlikesclouds** [comment]
I'm out of clues.

The issue seems to be caused by the new Intel HD Graphics drivers. People also reported the same crash issue to me and they all had Intel HD Graphics. I have one of these iGPUs, but I also have NVIDIA, just like you. Unfortunately, I cannot reproduce this crash, so it is super hard for me to debug it.

In the meantime, I'll be researching the solution for this problem.

**Comment by blueskythlikesclouds** [comment]
Hey, I've done some fixes.  b94c92b 
Could you two please test it?

You can download the latest development here:
https://ci.appveyor.com/project/blueskythlikesclouds/mikumikulibrary/build/artifacts

**Comment by Omoinemie** [comment]
> Hey, I've done some fixes. [b94c92b](https://github.com/blueskythlikesclouds/MikuMikuLibrary/commit/b94c92b2c57c0ac77bbe906f4d4e58ec7afe4968)
> Could you two please test it? @WM86 @Omoinemie
> 
> You can download the latest development build here:
> https://ci.appveyor.com/project/blueskythlikesclouds/mikumikulibrary/build/artifacts

same as before
![1](https://user-images.githubusercontent.com/31991443/49334772-c0420400-f618-11e8-9540-4a1fa2d6ac57.gif)

**Comment by Cainan-Corlett** [comment]
doesn't build 1803/1809 have a gpu switching feature

**Comment by Omoinemie** [comment]
> Hey, I've done some fixes. [b94c92b](https://github.com/blueskythlikesclouds/MikuMikuLibrary/commit/b94c92b2c57c0ac77bbe906f4d4e58ec7afe4968)
> Could you two please test it? @WM86 @Omoinemie
> 
> You can download the latest development build here:
> https://ci.appveyor.com/project/blueskythlikesclouds/mikumikulibrary/build/artifacts

I hava another PC in 1803 without Intel HD Graphics，but it still crashed when click the obj.bin

**Comment by Omoinemie** [comment]
> Are your drives up to date? I seriously can't think of anything else, the latest commit fixed issues for some people.

I opened a teamviewer remote desktop：ID: 872 939 160 PW：u3ng38

**Comment by blueskythlikesclouds** [comment]
@Omoinemie Do you have any place I can contact you? Like Discord

**Comment by Omoinemie** [comment]
> Are your drives up to date? I seriously can't think of anything else, the latest commit fixed issues for some people.

Discord ID：OmoineMie

**Comment by blueskythlikesclouds** [comment]
I also need your Discord tag number.

**Comment by Omoinemie** [comment]
> I also need your Discord tag number.

![snipaste_2018-12-02_17-47-13](https://user-images.githubusercontent.com/31991443/49338288-55b1b800-f65a-11e8-8e23-c3a4322a0ad2.jpg)

**Comment by blueskythlikesclouds** [comment]
For the time being, you could use the version that disables the model viewer:
https://ci.appveyor.com/project/blueskythlikesclouds/mikumikulibrary/builds/20708290/artifacts

**Comment by mitsu600** [comment]
I am using Ryzen and RTX 2080, I had problems with error in model view.
However
GL.Viewport (ClientRectangle);
An error was avoided by commenting out the above part.
However, the size was small, or when the window was resized the view got fat.
This was a report.
![samp](https://user-images.githubusercontent.com/35040965/51807767-a64a3800-22ce-11e9-8910-8cf525f5ae01.jpg)
![samp2](https://user-images.githubusercontent.com/35040965/51807768-ae09dc80-22ce-11e9-9984-69ccc691f350.jpg)

**Comment by blueskythlikesclouds** [comment]
This is interesting to know! I'll look into this when I have the chance.

**Comment by blueskythlikesclouds** [comment]
@mitsu600 Could you test the latest commit? 4d436b28
I managed to reproduce the crash, and possibly fixed it.

**Comment by mitsu600** [comment]
I appreciate your update.
That's excellent! It works perfectly.
Thank you very much.
![good](https://user-images.githubusercontent.com/35040965/52164103-74522f00-272f-11e9-86ba-c8abad0095c8.jpg)

**Comment by blueskythlikesclouds** [comment]
It seems the issue is finally fixed. I got more people to test the new build, and they all reported that it worked.

Feel free to reopen this issue if it still happens.
