### ISSUE TITLE
Replacing an item in Project DIVA F with one from Future Tone causes a crash in-game

### ISSUE THREAD

**Issue by featjinsoul** [blueskythlikesclouds/MikuMikuLibrary#30]
Hi,

As described in the title, replacing an item causes a crash in-game. Tested with both fresh installs of BLJM60527 and NPUB31241 1.00. Here are the following steps to reproduce the problem.

Create configurations for both Future Tone and F. Replace any item with one from Future Tone (I've tried Miku, Rin, and Luka's 001 item) and the game will crash with an unmapped memory violation in RPCS3. 

Interestingly, replacing even after editing and doing material fixup in another program like 3ds Max still causes this issue - even after removing maps that F does not use (using only Color and Specular textures). 

I'll try rolling back to a previous version of MML and MMM to see if the issue still persists.

**Comment by blueskythlikesclouds** [comment]
Huh. It works for me, though.
Can you try the unstable build, then?

**Comment by blueskythlikesclouds** [comment]
Fixed as of 6441881.
