### ISSUE TITLE
Broken sprites when modifying their coordinates (PD F 2ND)

### ISSUE THREAD

**Issue by Akatsukidarkx** [blueskythlikesclouds/MikuMikuLibrary#33]
When modifying the X/Y/height/width values of the sprites, they are loaded wrong in the game, although in the *.farc itself from MikuMikuModel they are displayed correctly.
Since PD F this doesn't happen, I'm in doubt if it should be edited differently  in 2nd. 
At first I thought it was due to the modified *.aet, but it happens the same keeping the original *.aet.

![1](https://user-images.githubusercontent.com/45851149/116332392-4685b480-a797-11eb-9215-1c5d4ed5384a.png)

[DIVA2ND-farcs.zip](https://github.com/blueskythlikesclouds/MikuMikuLibrary/files/6388482/DIVA2ND-farcs.zip)

**Comment by blueskythlikesclouds** [comment]
Should be fixed as of 0a4d8ba, please re-open the issue if the issue still persists.
