### ISSUE TITLE
Is BoneWeights Changed Its Name To BlendWeights And BlendIndices ?

### ISSUE THREAD

**Issue by Raspberry-Monster** [blueskythlikesclouds/MikuMikuLibrary#50]
Sorry for the disturbing. A friend of mine is working on old version of MFMK+ and he request me to complie this. However, after I checked the commit history, I saw that BoneWeights seems have been changed to BlendWeights and BlendIndices. Is that right? 

However, I would be appreciate if you can let me access the latest version of MFMK+. If I can't, the MFMK+ on my computer won't be leaked until the MFMK has been publicly released.

All in all, thank you for giving me a hand and hope you have a great day!

**Comment by Raspberry-Monster** [comment]
BTW, you can find me on Discord. My user name is raspberry_kan

**Comment by blueskythlikesclouds** [comment]
Why are you working with an old version? The shader will massively change when I return back to the project and all of your lighting modifications won't look correct anymore. I'd say don't waste your time with it.

**Comment by Raspberry-Monster** [comment]
> Why are you working with an old version? The shader will massively change when I return back to the project and all of your lighting modifications won't look correct anymore. I'd say don't waste your time with it.

Well, okay. Thank you for telling me.

The reason of why I am working on this is some modders think that the MFMK+ will bring a massive change to MM+ since they 're MFMK+ makes porting models possible. I am looking forward to the publicly release.

Thank you for replying me and please forgive me for making a rude request. Have a great day!

**Comment by Raspberry-Monster** [comment]
> Why are you working with an old version? The shader will massively change when I return back to the project and all of your lighting modifications won't look correct anymore. I'd say don't waste your time with it.

Well, okay. Thank you for telling me.

The reason of why I am working on this is some modders think that the MFMK+ will bring a massive change to MM+ since they 're MFMK+ makes porting models possible. I am looking forward to the publicly release.

Thank you for replying me and please forgive me for making a rude request. Have a great day!

**Comment by blueskythlikesclouds** [comment]
It's fine, just make sure you keep the files to yourself. Some unfortunate things happened with certain people back then so I'm not comfortable sharing the current version with people till I actually release it.

Closing this issue now.
