### ISSUE TITLE
Error: Invalid signature (expected FARC/FArC/FArc) when trying to use a farc file using FarcPack

### ISSUE THREAD

**Issue by BulArvs99** [blueskythlikesclouds/MikuMikuLibrary#51]
For some reason I can't open any farc files and when I tried to inspect the problem from the debugger it only spits out random characters and never the expected text

**Comment by blueskythlikesclouds** [comment]
I'm gonna assume you unpacked Mega Mix+'s CPK yourself. The files are encrypted, that's why you can't unpack them.

FarcPack can unpack the Mega Mix+ CPK files, extract using that first.

**Comment by blueskythlikesclouds** [comment]
Well?
