### ISSUE TITLE
Module Stamps do not load with ID over 1000

### ISSUE THREAD

**Issue by Platonic-DIVA** [blueskythlikesclouds/MikuMikuLibrary#54]
This is a base game issue, but a feature that should be added to DML at some point. Module stamps under photo_print/modules will not load once you surpass Module ID 999.

**Comment by blueskythlikesclouds** [comment]
Did you mean to post this in DivaModLoader repository?

**Comment by Platonic-DIVA** [comment]
yep, dont mind me :p
