### ISSUE TITLE
How To Get Auto Constraints

### ISSUE THREAD

**Issue by SonicGithub2024** [blueskythlikesclouds/MikuMikuLibrary#55]
I Wanna Try Auto Constraints, But I Don't Have The Option

**Comment by blueskythlikesclouds** [comment]
Get the unstable build from the README.
https://ci.appveyor.com/project/blueskythlikesclouds/mikumikulibrary/build/artifacts

(I queued a rebuild, you have to wait till it finishes, should be done in a bit)
