### ISSUE TITLE
error when trying to export textures or fbx files

### ISSUE THREAD

**Issue by catt569** [blueskythlikesclouds/MikuMikuLibrary#59]
![Captura_de_pantalla_71](https://github.com/user-attachments/assets/869b5aba-97ad-4b3a-a723-0dbf94978e4d)

**Comment by blueskythlikesclouds** [comment]
Did you install the redistributables like it says in the Releases page?

https://aka.ms/vs/16/release/VC_redist.x64.exe
https://aka.ms/vs/16/release/VC_redist.x86.exe
